version: "3"
services:
  syslog-server:
    # restart: unless-stopped
    container_name: syslog-server
    build: ./
    image: syslog-server:latest
    ports:
      - "514:514/udp"
      - "8765:80/tcp"
    volumes:
      - "./conf/syslog-server.json:/syslog-server/config.json"
      - "./conf/apache2.conf:/etc/apache2/apache2.conf"
      - "./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf"
      - "./db:/var/lib/mongodb"
